<a href="https://colab.research.google.com/github/mohammedayoub968/Python-Numpy/blob/main/Numpy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy Basic Exercises


In [1]:
import numpy as np

1. Get NumPy Version & Build Info

Write a Numpy program to get the Numpy version and show the Numpy build configuration.

In [ ]:
numpy_version = np.version.version
numpy_configuration = np.show_config()
print("Numpy version : " , numpy_version)
print("Numpy configuration : " , numpy_configuration)

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc


2. Help for NumPy Add Function

Write a NumPy program to get help with the add function

In [ ]:
#using function info() to get informations about build-in function in python
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

3. Test Any Non-Zero

Write a NumPy program to test if any of the elements of a given array are non-zero.

In [ ]:
array = np.array([[1 ,5 ,4 ,3 ,0] , [2 ,0 ,5 ,0 ,7]])
check_nonzeros = np.nonzero(array)
print(check_nonzeros) #return two arrays the dirst is row indixes and the second is the column indexes

(array([0, 0, 0, 0, 1, 1, 1]), array([0, 1, 2, 3, 0, 2, 4]))


4. Test None are Zero

Write a NumPy program to test whether none of the elements of a given array are zero.

In [ ]:
arr = np.array([[1 ,5 ,4 ,3 ,] , [2 ,10 ,5 ,-7]])
print("Original array : " , array)
print("check zeros : " , np.all(array))
print("----------------------------------------------")
print("Original array : " , arr)
print("check zeros : " , np.all(arr))

Original array :  [[1 5 4 3 0]
 [2 0 5 0 7]]
check zeros :  False
----------------------------------------------
Original array :  [[ 1  5  4  3]
 [ 2 10  5 -7]]
check zeros :  True


5. Test infinity of Elements

Write a NumPy program to test a given array element-wise for infinity or not

In [ ]:
print("Original array : " , array)
print("the logic T\F array" , np.isinf(array))
print("check the array have infinit value or not : " , np.any(np.isinf(array)))
print("---------------------------------------------")
a = np.array([1 , float("inf") , 5 ,7 ,-4])
print("Original array : " , a)
print("the logic T\F array" , np.isinf(a))
print("check the array have infinit value or not : " , np.any(np.isinf(a)))

Original array :  [[1 5 4 3 0]
 [2 0 5 0 7]]
the logic T\F array [[False False False False False]
 [False False False False False]]
check the array have infinit value or not :  False
---------------------------------------------
Original array :  [ 1. inf  5.  7. -4.]
the logic T\F array [False  True False False False]
check the array have infinit value or not :  True


6. Test Finiteness of Elements

Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a number).

In [ ]:
print("Original array : " , array)
print("the logic T\F array" , np.isfinite(array))
print("check the array have finite value or not : " , np.all(np.isfinite(array)))
print("---------------------------------------------")
a = np.array([1 , float("-inf") , 5 ,7 ,-4])
print("Original array : " , a)
print("the logic T\F array" , np.isfinite(a))
print("check the array have finite value or not : " , np.all(np.isfinite(a)))
print("---------------------------------------------")
b = np.array([1 , np.nan , 5 ,7 ,-4])
print("Original array : " , b)
print("the logic T\F array" , np.isfinite(b))
print("check the array have finite value or not : " , np.all(np.isfinite(b)))

Original array :  [[1 5 4 3 0]
 [2 0 5 0 7]]
the logic T\F array [[ True  True  True  True  True]
 [ True  True  True  True  True]]
check the array have finite value or not :  True
---------------------------------------------
Original array :  [  1. -inf   5.   7.  -4.]
the logic T\F array [ True False  True  True  True]
check the array have finite value or not :  False
---------------------------------------------
Original array :  [ 1. nan  5.  7. -4.]
the logic T\F array [ True False  True  True  True]
check the array have finite value or not :  False


In [ ]:
p_s = np.array([1, -2, np.inf, -np.inf, 0, 3.5])
res_of_posinf = np.isposinf(p_s)
res_of_neginf = np.isneginf(p_s)
print("Element-wise positive infinity check:", res_of_posinf)
print("Element-wise negative infinity check:", res_of_neginf)

Element-wise positive infinity check: [False False  True False False False]
Element-wise negative infinity check: [False False False  True False False]


7. Test for NaN

Write a NumPy program to test element-wise for NaN of a given array.

In [ ]:
print("Original array : " , array)
print("the logic T\F array" , np.isnan(array))
print("check the array have NaN value or not : " , np.any(np.isnan(array)))
print("---------------------------------------------")
a = np.array([1 , np.nan , 5 ,7 ,-4])
print("Original array : " , a)
print("the logic T\F array" , np.isnan(a))
print("check the array have NaN value or not : " , np.any(np.isnan(a)))
print("---------------------------------------------")


Original array :  [[1 5 4 3 0]
 [2 0 5 0 7]]
the logic T\F array [[False False False False False]
 [False False False False False]]
check the array have NaN value or not :  False
---------------------------------------------
Original array :  [ 1. nan  5.  7. -4.]
the logic T\F array [False  True False False False]
check the array have NaN value or not :  True
---------------------------------------------


8. Test for Complex/Real/Scalar

Write a NumPy program to test element-wise for complex numbers, real numbers in a given array. Also test if a given number is of a scalar type or not.

In [ ]:
print("Original array : " , array)
print("the logic T\F array" , np.iscomplex(array))
print("check the array have complex value or not : " , np.any(np.iscomplex(array)))
print("---------------------------------------------")
a = np.array([1 , 1+1j , 5 ,7 ,-4])
print("Original array : " , a)
print("the logic T\F array" , np.iscomplex(a))
print("check the array have complex value or not : " , np.any(np.iscomplex(a)))
print("---------------------------------------------")


Original array :  [[1 5 4 3 0]
 [2 0 5 0 7]]
the logic T\F array [[False False False False False]
 [False False False False False]]
check the array have complex value or not :  False
---------------------------------------------
Original array :  [ 1.+0.j  1.+1.j  5.+0.j  7.+0.j -4.+0.j]
the logic T\F array [False  True False False False]
check the array have complex value or not :  True
---------------------------------------------


In [ ]:
print("Original array : " , array)
print("the logic T\F array" , np.isreal(array))
print("check the array have real value or not : " , np.any(np.isreal(array)))
print("---------------------------------------------")
a = np.array([1 , 4.3 , 5 ,7 ,-4])
print("Original array : " , a)
print("the logic T\F array" , np.isreal(a))
print("check the array have real value or not : " , np.any(np.isreal(a)))
print("---------------------------------------------")


Original array :  [[1 5 4 3 0]
 [2 0 5 0 7]]
the logic T\F array [[ True  True  True  True  True]
 [ True  True  True  True  True]]
check the array have real value or not :  True
---------------------------------------------
Original array :  [ 1.   4.3  5.   7.  -4. ]
the logic T\F array [ True  True  True  True  True]
check the array have real value or not :  True
---------------------------------------------


In [ ]:
print("Original array : " , array)
print("the logic T\F array" , np.isscalar(array))
print("check the array have scalar value or not : " , np.any(np.isscalar(array)))
print("---------------------------------------------")
a = 3.4
print("Original array : " , a)
print("the logic T\F array :" , np.isscalar(a))
print("check the array have scalar value or not : " , np.any(np.isscalar(a)))
print("---------------------------------------------")


Original array :  [[1 5 4 3 0]
 [2 0 5 0 7]]
the logic T\F array False
check the array have scalar value or not :  False
---------------------------------------------
Original array :  3.4
the logic T\F array : True
check the array have scalar value or not :  True
---------------------------------------------


9. Test Element-Wise Tolerance Equality

Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

In [ ]:
print("Test if two arrays are element-wise equal within a tolerance:")

print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))
print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))
print(np.allclose([1e10,1e-8], [1.0001e10,1e-9]))

print(np.allclose([1.0, np.nan], [1.0, np.nan]))
print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True))


Test if two arrays are element-wise equal within a tolerance:
False
True
False
False
True


10. Element-Wise Comparison (Greater/Less)

Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [ ]:
x = np.array([3, 5])
y = np.array([2, 5])

print("Original Numbers : ")
print(x)
print(y)
print("Comparison - greater : " , np.greater(x,y))
print("Comparison - greater_equal : " , np.greater_equal(x,y))
print("Comparison - less : " , np.less(x,y))
print("Comparison - less_equal : " , np.less_equal(x,y))


Original Numbers : 
[3 5]
[2 5]
Comparison - greater :  [ True False]
Comparison - greater_equal :  [ True  True]
Comparison - less :  [False False]
Comparison - less_equal :  [False  True]


# NumPy Array Exercises

1. Convert List to 1D Array

Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.

Expected Output:

Original List: [12.23, 13.32, 100, 36.32]
One-dimensional NumPy array: [ 12.23 13.32 100. 36.32]

In [ ]:
my_list = [12.23, 13.32, 100, 36.32]
array = np.array(my_list)
print(array)
print(type(array))

[ 12.23  13.32 100.    36.32]
<class 'numpy.ndarray'>


2. Create 3x3 Matrix (2?10)

Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

Expected Output:

[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]

In [ ]:
a = np.arange(2,11).reshape(3,3)
print(a)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
my_list = [[2 , 3 , 4], [ 5, 6, 7] ,[ 8 ,9 ,10]]
array = np.array(my_list)
print(array)
print(array.shape)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
(3, 3)


3. Null Vector (10) & Update Sixth Value

Write a NumPy program to create a null vector of size 10 and update the sixth value to 11.

[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [ ]:
array = np.zeros(10)
print("The original array : ",array)
array[6] = 11
print("Update the sixth value in the array :to 11 " , array)

The original array :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update the sixth value in the array :to 11  [ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


5. Array from 12 to 38

Write a NumPy program to create an array with values ranging from 12 to 38.

Expected Output:

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]



In [ ]:
array = np.arange(12,38)
print(array)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


6. Reverse Array

Write a NumPy program to reverse an array (the first element becomes the last).

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [ ]:
original = np.arange(12,38)
print("The original array : \n" , original)
reverse = original[::-1]
print("The reversed array : \n" , reverse)

The original array : 
 [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
The reversed array : 
 [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


7. Convert Array to Float Type

Write a NumPy program to convert an array to a floating type.

Sample output:

Original array
[1, 2, 3, 4]

Array converted to a float type:
[ 1. 2. 3. 4.]

In [ ]:
array = np.array([[1 , 5 ,7] , [4 , 7 ,9]])
print("The original array data type : " , array.dtype)
array = array.astype("float32")
print("The converted array data type : " , array.dtype)

The original array data type :  int64
The converted array data type :  float32


8. 2D Array (Border 1, Inside 0)

Write a NumPy program to create a 2D array with 1 on the border and 0 inside.

Expected Output:

Original array:
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]

1 on the border and 0 inside in the array
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]

In [ ]:
original = np.ones((5,5))
print("Original Array : \n",original)
print("-----------------------------------")
original[1:-1 , 1:-1] = 0
print("Border Array : \n",original)


Original Array : 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
-----------------------------------
Border Array : 
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9. Add Border to Array (0s)

Write a NumPy program to add a border (filled with 0's) around an existing array.

Expected Output:

Original array:
[[ 1. 1. 1.]
[ 1. 1. 1.]
[ 1. 1. 1.]]

1 on the border and 0 inside in the array
[[ 0. 0. 0. 0. 0.]
...........
[ 0. 0. 0. 0. 0.]]

In [ ]:
original = np.zeros((5,5))
print("Original Array : \n",original)
print("-----------------------------------")
original[1:-1 , 1:-1] = 1
print("Border Array : \n",original)


Original Array : 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
-----------------------------------
Border Array : 
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


10. 8x8 Checkerboard Pattern

Write a NumPy program to create an 8x8 matrix and fill it with a checkerboard pattern.

Checkerboard pattern:

[[0 1 0 1 0 1 0 1]
..........
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]


In [ ]:
original  = np.zeros((8,8) , dtype= "int8")
print("Original Array : \n",original)

original[1::2 , ::2] = 1
original[::2 , 1::2] = 1

print("Checkerboard Pattern Array : \n",original)


Original Array : 
 [[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
Checkerboard Pattern Array : 
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


11. List/Tuple to Arrays

Write a NumPy program to convert a list and tuple into arrays.

List to array:
[1 2 3 4 5 6 7 8]

Tuple to array:
[[8 4 6]
[1 2 3]]

In [ ]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8]
my_tuple = ([8 , 4 , 6] , [1 ,2 ,3])

list_to_array = np.array(my_list)
tuple_to_array  = np.array(my_tuple)

print("The original list : " , my_list)
print("list to array : " , list_to_array)
print("-----------------------------------")
print("The original tuple : " , my_tuple)
print("tuple to array : \n" , tuple_to_array)


The original list :  [1, 2, 3, 4, 5, 6, 7, 8]
list to array :  [1 2 3 4 5 6 7 8]
-----------------------------------
The original tuple :  ([8, 4, 6], [1, 2, 3])
tuple to array : 
 [[8 4 6]
 [1 2 3]]


12. Append Values to Array

Write a NumPy program to append values to the end of an array.

Expected Output:

Original array:
[10, 20, 30]

After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]

In [ ]:
array = np.array([10 , 20 , 30])
print("original array : \n" , array)
array2 = np.append(array , [40 ,50 ,60 ,70 ,80 ,90])
print("append values 40 , 50 ,60 ,70 ,80 ,90 to the array : \n" , array2)

original array : 
 [10 20 30]
append values 40 , 50 ,60 ,70 ,80 ,90 to the array : 
 [10 20 30 40 50 60 70 80 90]


13. Create Empty and Full Array

Write a NumPy program to create an empty and full array.

Expected Output:

[ 6.93270651e-310 1.59262180e-316 6.93270559e-310 6.93270665e-310]
[ 6.93270667e-310 6.93270671e-310 6.93270668e-310 6.93270483e-310]
[ 6.93270668e-310 6.93270671e-310 6.93270370e-310 6.93270488e-310]]
[[6 6 6]
[6 6 6]
[6 6 6]]

In [ ]:
empty_array = np.empty((4,4) , dtype= "int8")
full_array = np.full((4,4) , fill_value= 6)

print("The empty array is : \n" , empty_array)
print("--------------------------------------------")
print("The full array is : \n" , full_array)


The empty array is : 
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
--------------------------------------------
The full array is : 
 [[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


14. Celsius to Fahrenheit Conversion

Write a NumPy program to convert Centigrade degrees into Fahrenheit degrees. Centigrade values are stored in a NumPy array.

Sample Array [0, 12, 45.21, 34, 99.91]
[-17.78, -11.11, 7.34, 1.11, 37.73, 0. ]

Expected Output:

Values in Fahrenheit degrees:
[ 0. 12. 45.21 34. 99.91 32. ]

Values in Centigrade degrees:
[-17.78 -11.11 7.34 1.11 37.73 0. ]

Values in Centigrade degrees:
[-17.78 -11.11 7.34 1.11 37.73 0. ]

Values in Fahrenheit degrees:
[-0. 12. 45.21 34. 99.91 32. ]

In [ ]:
Celsius_array = np.array([0 ,12 ,45.21 ,34 ,99.91])
Fahrenheit_array = Celsius_array * 1.8 +32
print(Fahrenheit_array)

[ 32.     53.6   113.378  93.2   211.838]


15. Array Elements Count & Memory Usage

Write a NumPy program to find the number of elements in an array. It also finds the length of one array element in bytes and the total bytes consumed by the elements.

Expected Output:

Size of the array: 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24

In [ ]:
arr = np.array([10 , 25 , 33 , 44])
n_elements = arr.size
print("array : " , arr)
print("number of elements in an array : " , n_elements)
length_one_esize = arr.itemsize
print("length of one array element in bytes : " ,length_one_esize)
total_bytes = arr.nbytes
print("total bytes consumed by the elements : " , total_bytes)

array :  [10 25 33 44]
number of elements in an array :  4
length of one array element in bytes :  8
total bytes consumed by the elements :  32


16. 1D Array Element Check in Another Array

Write a NumPy program to test whether each element of a 1-D array is also present in a second array.

Expected Output:

Array1: [ 0 10 20 40 60]
Array2: [0, 40]

Compare each element of array1 and array2
[ True False False True False]

In [ ]:
a1 = np.array([0 , 10 ,20 ,40 ,60])
a2 = np.array([0 ,40])
print(np.in1d(a1,a2))

[ True False False  True False]


/tmp/ipython-input-13-3176497671.py:3: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  print(np.in1d(a1,a2))


17. Unique Elements of Array

Write a NumPy program to get the unique elements of an array.

Expected Output:

Original array:

[10 10 20 20 30 30]

Unique elements of the above array:
[10 20 30]

Original array:
[[1 1]
[2 3]]

Unique elements of the above array:
[1 2 3]

In [ ]:
a = np.array([10 , 10 ,20 ,20 ,30 ,30])
uniqe = np.unique(a)
print("original array : " , a)
print("uniqe array : " , uniqe)

original array :  [10 10 20 20 30 30]
uniqe array :  [10 20 30]


18. Set Difference of Arrays

Write a NumPy program to find the set difference between two arrays. The set difference will return sorted, distinct values in array1 that are not in array2.

Expected Output:

Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70, 90]

Set difference between two arrays:
[ 0 20 60 80]

In [ ]:
a1 = np.array([0 , 10 ,20 ,40 ,60])
a2 = np.array([0 ,40])
print(np.setdiff1d(a1 , a2))

[10 20 60]


19. Union of Two Arrays

Write a NumPy program to find the union of two arrays. Union will return a unique, sorted array of values in each of the two input arrays.

Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70]

Unique sorted array of values that are in either of the two input arrays:
[ 0 10 20 30 40 50 60 70 80]



In [ ]:
a1 = np.array([0, 10, 20, 40 ,60 ,80])
a2 = np.array([10, 30, 40, 50, 70])
print("the union : " ,np.union1d(a1 , a2))

the union :  [ 0 10 20 30 40 50 60 70 80]


20. Indices of Max/Min Along Axis

Write a NumPy program to find the indices of the maximum and minimum values along the given axis of an array.

Original array: [1 2 3 4 5 6]

Maximum Values: 5
Minimum Values: 0

In [ ]:
a = np.array([1,2,3,4,5,6])
print("Maximum index : " , np.argmax(a))
print("Minumun index : " , np.argmin(a))

Maximum index :  5
Minumun index :  0


# NumPy Statistics: Mean, Median, Covariance Exercises

1. Maximum and Minimum of Flattened Array

Write a Python program to find the maximum and minimum value of a given flattened array.


Expected Output:
Original flattened array:
[[0 1]
[2 3]]
Maximum value of the above flattened array:
3
Minimum value of the above flattened array:
0

In [ ]:
a = np.array([[0,1] , [2 , 3]])
print("The original array : \n", a)
b = a.flatten()
print("array after flateen : ",b)
print("The maximum value of the flatten array is : " , b.max())
print("The minumum value of the flatten array is : " , b.min())

The original array : 
 [[0 1]
 [2 3]]
array after flateen :  [0 1 2 3]
The maximum value of the flatten array is :  3
The minumum value of the flatten array is :  0


2. Minimum and Maximum Along Second Axis

Write a NumPy program to get the minimum and maximum value of a given array along the second axis.

Expected Output:
Original array:
[[0 1]
[2 3]]
Maximum value along the second axis:
[1 3]
Minimum value along the second axis:
[0 2]

In [ ]:
print("The original array : \n", a)
print("The max value in x-axis is : " , a.max(axis=1))
print("The min value in x-axis is : " , a.min(axis=1))

The original array : 
 [[0 1]
 [2 3]]
The max value in x-axis is :  [1 3]
The min value in x-axis is :  [0 2]


3. 80th Percentile Along Second Axis

Write a NumPy program to compute the 80th percentile for all elements in a given array along the second axis.

In [ ]:
x = np.arange(12).reshape((2, 6))

print("\nOriginal array:")
print(x)
r1 = np.percentile(x, 80, 1)

print("\n80th percentile for all elements of the said array along the second axis:")
print(r1)



Original array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

80th percentile for all elements of the said array along the second axis:
[ 4. 10.]


4. Median of Flattened Array

Write a NumPy program to compute the median of flattened given array.

Note: First array elements raised to powers from second array
Expected Output:
Original array:
[[ 0 1 2 3 4 5]
[ 6 7 8 9 10 11]]
Median of said array:
5.5

In [ ]:
a = np.array([[ 0,  1, 2,3, 4, 5], [ 6, 7, 8, 9, 10, 11]])
flatten_array = a.flatten()
print("the median of the flatten array is : ", np.median(flatten_array))

the median of the flatten array is :  5.5


5. Weighted Average of an Array

Write a NumPy program to compute the weighted of a given array.


Sample Output:
Original array:
[0 1 2 3 4]
Weighted average of the said array:
2.6666666666666665

In [ ]:
a = np.array([0 , 1 ,2 ,3 ,4])
print("the wegited average is : " , np.mean(a))

the wegited average is :  2.0


6. Mean, Standard Deviation, and Variance Along Second Axis

Write a NumPy program to compute the mean, standard deviation, and variance of a given array along the second axis.

Sample output:
Original array:
[0 1 2 3 4 5]
Mean: 2.5
std: 1
variance: 2.916666666666666

In [ ]:
a = np.array([0 , 1 ,2 ,3 ,4 , 5])
print("the wegited average is : " , np.mean(a))
print("the wegited std is : " , np.std(a))
print("the wegited var is : " , np.var(a))

the wegited average is :  2.5
the wegited std is :  1.707825127659933
the wegited var is :  2.9166666666666665


7. Covariance Matrix of Two Arrays

Write a NumPy program to compute the covariance matrix of two given arrays.

Sample Output:
Original array1:
[0 1 2]
Original array1:
[2 1 0]
Covariance matrix of the said arrays:
[[ 1. -1.]
[-1. 1.]]

In [ ]:
a1 = np.array([0 , 1 , 2 ])
a2 = np.array([2 , 1 ,0])
np.cov(a1 , a2)

array([[ 1., -1.],
       [-1.,  1.]])

8. Cross-Correlation of Two Arrays

Write a NumPy program to compute cross-correlation of two given arrays.

Sample Output:
Original array1:
[0 1 3]
Original array1:
[2 4 5]
Cross-correlation of the said arrays:
[19]

In [ ]:
a1 = np.array([0 , 1 , 3])
a2 = np.array([2 , 4 ,5])
np.correlate(a1 , a2)

array([19])

9. Pearson Product-Moment Correlation Coefficients

Write a NumPy program to compute pearson product-moment correlation coefficients of two given arrays.

Sample Output:
Original array1:
[0 1 3]
Original array1:
[2 4 5]
Pearson product-moment correlation coefficients of the said arrays:
[[1. 0.92857143]
[0.92857143 1. ]]

In [ ]:
a1 = np.array([0 , 1 , 3])
a2 = np.array([2 , 4 ,5])
np.corrcoef(a1 , a2)

array([[1.        , 0.92857143],
       [0.92857143, 1.        ]])

10. Weighted Average Along Specified Axis of a Flattened Array

Write a Python NumPy program to compute the weighted average along the specified axis of a given flattened array.

From Wikipedia: The weighted arithmetic mean is similar to an ordinary arithmetic mean (the most common type of average), except that instead of each of the data points contributing equally to the final average, some data points contribute more than others. The notion of weighted mean plays a role in descriptive statistics and also occurs in a more general form in several other areas of mathematics.

Sample output:
Original flattened array:
[[0 1 2]
[3 4 5]
[6 7 8]]
Weighted average along the specified axis of the above flattened array:
[1.2 4.2 7.2]

In [ ]:
a = np.array([[0 , 1 , 2] , [3 , 4 ,5] , [6 , 7 ,8]])
weights = [1 , 2 ,3]
np.average(a ,axis=0 , weights=weights)

array([4., 5., 6.])

#NumPy Advanced Indexing:

1. 2D Array Random Integers & Boolean Indexing

Write a NumPy program that creates a 2D NumPy array of random integers. Use boolean indexing to select all elements greater than a specified value.

In [10]:
a = np.random.randint(0 ,100 ,size= (5,5))
th = 50
b = a[a>th]
print('Original 2D array:\n', a)
print(f'\nElements greater than {th}:\n', b)

Original 2D array:
 [[ 7  9 70 52  0]
 [52 70 40  2 79]
 [21 44  7  9 13]
 [80 18 70 61 16]
 [16 10 88 61 31]]

Elements greater than 50:
 [70 52 52 70 79 80 70 61 88 61]


2. 1D Array & Integer Array Indexing

Write a NumPy program that creates a 1D NumPy array and uses integer array indexing to select a subset of elements based on an index array.

In [11]:
array_1d = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

index_array = np.array([0, 2, 4, 6, 8])

selected_elements = array_1d[index_array]

print('Original 1D array:\n', array_1d)
print('Index array:\n', index_array)
print('Selected elements:\n', selected_elements)


Original 1D array:
 [ 10  20  30  40  50  60  70  80  90 100]
Index array:
 [0 2 4 6 8]
Selected elements:
 [10 30 50 70 90]


3. 4D Array & Multi-dimensional Indexing

Multi-dimensional Indexing:

Write a NumPy program that creates a 4D NumPy array and uses multi-dimensional indexing to select a subarray.

In [12]:
array_4d = np.random.randint(0, 100, size=(3, 4, 5, 6))


subarray = array_4d[:2, :3, :4, :5]

print('Original 4D array shape:', array_4d.shape)
print('Selected subarray shape:', subarray.shape)
print('Selected subarray:\n', subarray)


Original 4D array shape: (3, 4, 5, 6)
Selected subarray shape: (2, 3, 4, 5)
Selected subarray:
 [[[[33 51 55 52 18]
   [93 92 51 23 38]
   [74 87 55 26  5]
   [95 18 59  9 37]]

  [[ 9 44 84 66 90]
   [40  9 69 53 57]
   [43 61 80 11 96]
   [25 52 20  4 18]]

  [[27 76 17 41 19]
   [48 40 74 78 24]
   [71 40 80 78 92]
   [32 94 57 92 39]]]


 [[[16 19 98 24 32]
   [46 30 22 21 81]
   [42 41 95 49 97]
   [64 55 33 18 11]]

  [[87 13 13 72 34]
   [94 46 94 24 66]
   [77 60 94 18 14]
   [46 21 60 20 15]]

  [[17 27 34 61  5]
   [99  9  4 70 79]
   [61 11 86 28 93]
   [70 63 50 55 43]]]]


4. 2D Random Floats & Multiple Condition Boolean Indexing

Boolean Indexing with Conditions:

Write a NumPy program that creates a 2D NumPy array of random floats and uses boolean indexing to select elements that satisfy multiple conditions (e.g., greater than 0.5 and less than 0.8).

In [13]:
array_2d = np.random.rand(5, 5)

condition1 = array_2d > 0.5
condition2 = array_2d < 0.8

selected_elements = array_2d[condition1 & condition2]

print('Original 2D array:\n', array_2d)
print('Elements greater than 0.5 and less than 0.8:\n', selected_elements)


Original 2D array:
 [[0.9061356  0.33389125 0.88871923 0.75639905 0.8623062 ]
 [0.5964211  0.77820325 0.31831768 0.97775707 0.34182002]
 [0.33791928 0.41716352 0.32819565 0.67268289 0.44387764]
 [0.68446535 0.75528963 0.34917129 0.26977818 0.64115921]
 [0.72398085 0.99065    0.04057982 0.76195775 0.82638995]]
Elements greater than 0.5 and less than 0.8:
 [0.75639905 0.5964211  0.77820325 0.67268289 0.68446535 0.75528963
 0.64115921 0.72398085 0.76195775]


5. Sort Array Along Different Axes

Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array.

In [14]:
a = np.array([[10, 40], [30, 20]])

print("Original array:")
print(a)

print("Sort the array along the first axis:")
print(np.sort(a, axis=0))

print("Sort the array along the last axis:")
print(np.sort(a))

print("Sort the flattened array:")
print(np.sort(a, axis=None))


Original array:
[[10 40]
 [30 20]]
Sort the array along the first axis:
[[10 20]
 [30 40]]
Sort the array along the last axis:
[[10 40]
 [20 30]]
Sort the flattened array:
[10 20 30 40]


6. Structured Array Sorted by Height

Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort the array on height.

Sample Output:
Original array:
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
(b'Pit', 5, 40.11)]
Sort by height
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
(b'Nail', 6, 52.5 )]

In [15]:
data_type = [('name', 'S15'), ('class', int), ('height', float)]

students_details = [('James', 5, 48.5), ('Nail', 6, 52.5), ('Paul', 5, 42.10), ('Pit', 5, 40.11)]

students = np.array(students_details, dtype=data_type)

print("Original array:")
print(students)

print("Sort by height")
print(np.sort(students, order='height'))


Original array:
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
 (b'Pit', 5, 40.11)]
Sort by height
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


7. Structured Array Sorted by Class Then Height

Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort by class, then height if class are equal.

Expected Output:
Original array:
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 ) (b'Pit', 5, 40.11)]
Sort by age, then height if class are equal:
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 ) (b'Nail', 6, 52.5 )]

In [17]:
data_type = [('name', 'S15'), ('class', int), ('height', float)]

students_details = [('James', 5, 48.5), ('Nail', 6, 52.5), ('Paul', 5, 42.10), ('Pit', 5, 40.11)]

students = np.array(students_details, dtype=data_type)

print("Original array:")
print(students)

print("Sort by class, then height if class are equal:")
print(np.sort(students, order=['class', 'height']))


Original array:
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
 (b'Pit', 5, 40.11)]
Sort by class, then height if class are equal:
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


8. Sort Student IDs by Increasing Height

Write a NumPy program to sort the student id with increasing height of the students from given students id and height. Print the integer indices that describes the sort order by multiple columns and the sorted data.

Expected Output:
Sorted indices:
[4 0 5 3 6 1 2]
Sorted data:
1682 38.0
1023 40.0
5241 40.0
1671 41.0
4532 42.0
5202 42.0
6230 45.0

In [18]:
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
student_height = np.array([40., 42., 45., 41., 38., 40., 42.0])

indices = np.lexsort((student_id, student_height))

print("Sorted indices:")
print(indices)

print("Sorted data:")
for n in indices:
    print(student_id[n], student_height[n])


Sorted indices:
[4 0 5 3 6 1 2]
Sorted data:
1682 38.0
1023 40.0
5241 40.0
1671 41.0
4532 42.0
5202 42.0
6230 45.0


9. Sort Array by Nth Column

Write a NumPy program to sort an given array by the nth column.

Original array:
[[1 5 0]
[3 2 5]
[8 7 6]]
Sort the said array by the nth column:
[[3 2 5]
[1 5 0]
[8 7 6]]

In [19]:
print("Original array:\n")

nums = np.random.randint(0, 10, (3, 3))

print(nums)

print("\nSort the said array by the nth column: ")

print(nums[nums[:, 1].argsort()])


Original array:

[[9 1 8]
 [8 4 6]
 [2 6 9]]

Sort the said array by the nth column: 
[[9 1 8]
 [8 4 6]
 [2 6 9]]


10. Random Normal Numbers

Write a NumPy program to generate five random numbers from the normal distribution.

Expected Output:
[-0.43262625 -1.10836787 1.80791413 0.69287463 -0.53742101]

In [20]:
x = np.random.normal(size=5)

print(x)


[ 1.6966626   2.0520365   1.12443882  1.31118765 -1.73581136]


11. Random Integers in Range

Write a NumPy program to generate six random integers between 10 and 30.

In [21]:
x = np.random.randint(low=10, high=30, size=6)

print(x)


[12 15 15 10 10 29]


12. 3x3x3 Random Array

Write a NumPy program to create a 3x3x3 array with random values.

In [22]:
x = np.random.random((3, 3, 3))
print(x)


[[[0.08688406 0.94282601 0.32282204]
  [0.00878345 0.09539735 0.51947   ]
  [0.62750788 0.2775691  0.83651979]]

 [[0.82431627 0.85387955 0.5422267 ]
  [0.17000743 0.54777559 0.94240851]
  [0.83559829 0.12976135 0.37983952]]

 [[0.30910668 0.85900043 0.09867227]
  [0.13818475 0.542355   0.38185608]
  [0.67671067 0.20560909 0.85009838]]]


13. 5x5 Array Min/Max

Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.

In [23]:
x = np.random.random((5, 5))

print("Original Array:")
print(x)

xmin, xmax = x.min(), x.max()

print("Minimum and Maximum Values:")
print(xmin, xmax)


Original Array:
[[0.06223091 0.88937788 0.02905456 0.08858475 0.4451683 ]
 [0.80754313 0.96346548 0.4494492  0.46113746 0.56546649]
 [0.34032878 0.4328666  0.15868666 0.06530394 0.97461384]
 [0.16975662 0.03967013 0.76188256 0.93565608 0.26613061]
 [0.68951144 0.05451047 0.05133269 0.36409804 0.87919765]]
Minimum and Maximum Values:
0.02905456082821689 0.9746138377815047


14. Extract First 5 Rows of 10x4 Array

Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable.

In [24]:
x = np.random.rand(10, 4)

print("Original array:")
print(x)

y = x[:5, :]

print("First 5 rows of the above array:")
print(y)


Original array:
[[0.74146796 0.02425995 0.7185032  0.07941903]
 [0.71564044 0.88537457 0.82626552 0.61056115]
 [0.17370696 0.04014159 0.4445174  0.64934804]
 [0.31243535 0.16835026 0.92314943 0.25574844]
 [0.26168468 0.95246747 0.05003676 0.8393783 ]
 [0.65276761 0.42476302 0.46409    0.17136794]
 [0.6715793  0.54669135 0.1582544  0.23810325]
 [0.31223013 0.51696291 0.39815904 0.94240277]
 [0.74790118 0.39191979 0.56256399 0.93800553]
 [0.3914559  0.18365883 0.68890901 0.66127853]]
First 5 rows of the above array:
[[0.74146796 0.02425995 0.7185032  0.07941903]
 [0.71564044 0.88537457 0.82626552 0.61056115]
 [0.17370696 0.04014159 0.4445174  0.64934804]
 [0.31243535 0.16835026 0.92314943 0.25574844]
 [0.26168468 0.95246747 0.05003676 0.8393783 ]]


15. Shuffle Numbers 0-10

Write a NumPy program to shuffle numbers between 0 and 10 (inclusive).

Sample Output:
[5 7 9 0 2 3 1 6 8 4]
Same result using permutation():
[6 7 4 5 8 2 3 9 0 1]

In [25]:
x = np.arange(10)

np.random.shuffle(x)

print(x)


print("Same result using permutation():")
print(np.random.permutation(10))


[0 9 3 5 8 6 2 1 7 4]
Same result using permutation():
[8 1 7 4 2 9 0 6 3 5]


16. Normalize a 3x3 Matrix

Write a NumPy program to normalize a 3x3 random matrix.

In [26]:
x = np.random.random((3, 3))

print("Original Array:")
print(x)

xmax, xmin = x.max(), x.min()

x = (x - xmin) / (xmax - xmin)

print("After normalization:")
print(x)


Original Array:
[[0.78758443 0.83157158 0.57176632]
 [0.87382557 0.19163899 0.84521815]
 [0.28641072 0.41115103 0.08760546]]
After normalization:
[[0.89030917 0.94625679 0.61580828]
 [1.         0.13232113 0.96361399]
 [0.25286209 0.41152034 0.        ]]


17. Sort Random Vector of Size 10

Write a NumPy program to create a random vector of size 10 and sort it

In [27]:
x = np.random.random(10)

print("Original array:")
print(x)

x.sort()

print("Sorted array:")
print(x)


Original array:
[0.00942188 0.6773377  0.79940825 0.19700648 0.68507288 0.73101553
 0.40510103 0.85828763 0.11263726 0.07874107]
Sorted array:
[0.00942188 0.07874107 0.11263726 0.19700648 0.40510103 0.6773377
 0.68507288 0.73101553 0.79940825 0.85828763]


18. Find Nearest Value in Array

Write a NumPy program to find the nearest value from a given value in an array.

In [28]:
x = np.random.uniform(1, 12, 5)

v = 4

n = x.flat[np.abs(x - v).argmin()]

print(n)


4.077090155251678


19. Check Array Equality

Write a NumPy program to check two random arrays are equal or not.

Sample Output:
First array:
[1 0 1 0 1 1]
Second array:
[0 0 1 1 1 0]
Test above two arrays are equal or not!
False

In [29]:
x = np.random.randint(0, 2, 6)

print("First array:")
print(x)

y = np.random.randint(0, 2, 6)

print("Second array:")
print(y)

array_equal = np.allclose(x, y)

print("Test above two arrays are equal or not!")
print(array_equal)


First array:
[1 1 1 1 0 0]
Second array:
[0 0 1 0 0 0]
Test above two arrays are equal or not!
False


20. Write a NumPy program to find the dot product of two arrays of different dimensions.

In [30]:
nums1 = np.array([[1, 2], [3, 4], [5, 6]])
nums2 = np.array([7, 8])
print("Original arrays:")
print(nums1)
print(nums2)
result = np.dot(nums1, nums2)
print("Dot product of the said two arrays:")
print(result)


Original arrays:
[[1 2]
 [3 4]
 [5 6]]
[7 8]
Dot product of the said two arrays:
[23 53 83]
